config/routes.rb
Rails.application.routes.draw do

  resources :devices do
    post 'req', on: :member
  end

  resources :products

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks",
                                  :devise_session => "users/sessions",
                                  :devise_registration => "users/registrations"}
 

get '/requests/inqueue', to: 'requests#inqueue', as: 'inqueue_requests'
get '/requests/completed', to: 'requests#completed', as: 'completed_requests'

get '/index', to: 'main#index', as: 'main'

post '/getdevice/:id', to: 'devices#get_device', as: 'getdevice'

get '/users/getimage', to: 'user_info#send_image', as: 'image'

resource :user_info, path: '/user/info', except: [:index, :destroy]

mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

   root 'main#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
=begin

        user ||= User.new # guest user (not logged in)
       if user.is_admin == 1
         can :manage, :all
       elsif user.is_admin == 0
         can :manage, :Device
         can :manage, :Product
       end
=end



        if user.is_admin == 1
            can :manage, :all
        elsif user.is_admin == 0
            can [:index, :get_device, :assign_device, :show, :request_device], Device
            can :manage, UserInfo
            can [:inqueue], Request
        end



    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/device.rb
class Device < ActiveRecord::Base
	has_many :devicequeues
	has_many :users, through: :devicequeues
	
	belongs_to :deviceOwner, class_name: "User", validate: true
	belongs_to :request, class_name: "Request", foreign_key: "id", primary_key: "device_id"
end

app/models/device_queue.rb
class DeviceQueue < ActiveRecord::Base
	belongs_to :user
	belongs_to :device
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base

	def self.create_device_types
		DeviceType.create(id: 1,device_type: "phone")
		DeviceType.create(id: 2,device_type: "tablet")
		DeviceType.create(id: 3,device_type: "desktop")
	end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :request, validate: true
	validates :sender_id, :user_id, :request, presence: true
	belongs_to :user, validate: true
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/request.rb
class Request < ActiveRecord::Base
	has_one :notification
	has_one :device, class_name: "Device", primary_key: "device_id", foreign_key: "id"

	belongs_to :user, class_name: "User", foreign_key: "sender_id"
	belongs_to :user, class_name: "User", foreign_key: "reciever_id"
	def self.inqueue
		Request.where(status: 4)
	end

	def self.completed
		Request.where.not(status: 4)
	end
end

app/models/request_status.rb
class RequestStatus < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, 
  :trackable, :validatable, :omniauthable

  has_many :devicequeues
  has_many :devices, through: :devicequeues
  has_many :deviceOwner, class_name: "Device"
  has_one  :userinfo, class_name: "UserInfo"
  has_many :admin_requests, foreign_key: :reciever_id, class_name: "Request"
  has_many :user_requests, foreign_key: :sender_id, class_name: "Request"
  has_many :notifications

  def self.user_info(auth,user_id)

        info=auth.info
        extra=auth.extra

    #spliting firstname and lastname
        name=info.name
        name=name.split(" ")
        firstname=name[0]
        lastname=name[1]

    #finding date of birth
        #dob=extra.raw_info.birthday.to_s
        puts auth.to_yaml
        #dob=Date.parse(dob)  

    #getting image from google url
        require 'open-uri'
        open('public/image.png', 'wb') do |file|
          file << open(extra.raw_info.picture).read
        end

        UserInfo.create(user_id: user_id, first_name: firstname, last_name: lastname, gender: extra.raw_info.gender, 
        image_name: info.name )
  end


  def self.from_google_auth(auth)
    error = where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.reset_password_token = Devise.friendly_token[0,10]
      user.sign_in_count = user.sign_in_count + 1
      user.current_sign_in_at = DateTime.now
      user.last_sign_in_at = DateTime.now
      user.is_admin = 0
    end


   # current_user=User.find_by(email: auth.info.email)
   #userinfo=UserInfo.find_by(user_id: current_user.id)

    #if(userinfo != nil)
    #  User.user_info(auth,current_user.id)
    #end

  end

  def self.create_admin

    error = create do |user|
      user.provider = "DevTrack"
      user.uid = 1
      user.email = "admin@admin.com"
      user.password = "admin123"
      user.reset_password_token = Devise.friendly_token[0,10]
      user.sign_in_count = user.sign_in_count + 1
      user.current_sign_in_at = DateTime.now
      user.last_sign_in_at = DateTime.now
      user.is_admin = 1
    end

  end

  def self.user_exist?(username, password)
    user = find_by_email(username)

    if user != nil
      status = user.valid_password?(password)
      if status == true
        return user
      else
        return "Invalid Password"
      end
    else
      return "User not exist"
    end
  end





end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base

	belongs_to :user, validate: true, class_name: "User"
	
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :user_id, presence: true, uniqueness: true
	validates :gender, presence: true

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  before_action :authenticate_user!
  layout "controller_layouts" 
  
  respond_to :html, :json, :js
  def index
  	respond_to do |format|
  		format.html
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/helpers/user_info_helper.rb
module UserInfoHelper
end

app/views/layouts/_footer.html.erb
<!-- start: FOOTER -->
<div class="footer clearfix">
  <div class="footer-inner">
    2014 &copy; clip-one by cliptheme.
    <%= link_to "password_change", edit_user_registration_path %>
  </div>
  <div class="footer-items">
    <span class="go-top"><i class="clip-chevron-up"></i></span>
  </div>
</div>
<!-- end: FOOTER -->

app/views/layouts/_head.html.erb
<!DOCTYPE html>
<!-- Template Name: Clip-One - Responsive Admin Template build with Twitter Bootstrap 3.x Version: 1.3 Author: ClipTheme -->
<!--[if IE 8]><html class="ie8 no-js" lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9 no-js" lang="en"><![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- start: HEAD -->
<head>
  <title>Clip-One - Responsive Admin Template</title>
  <!-- start: META -->
  <meta charset="utf-8" />
  <!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta content="" name="description" />
  <meta content="" name="author" />
  <!-- end: META -->

</head>

app/views/layouts/_header.html.erb
<!-- start: HEADER -->

<div class="navbar navbar-inverse navbar-fixed-top">
<!-- start: TOP NAVIGATION CONTAINER -->
<div class="container">
<div class="navbar-header">
  <!-- start: RESPONSIVE MENU TOGGLER -->
  <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
    <span class="clip-list-2"></span>
  </button>
  <!-- end: RESPONSIVE MENU TOGGLER -->
  <!-- start: LOGO -->
  <a class="navbar-brand" href="<%= root_path %>" >
    Dev<i class="fa-laptop"></i>Track
  </a>
  <!-- end: LOGO -->
</div>
<div class="navbar-tools">
<!-- start: TOP NAVIGATION MENU -->
<ul class="nav navbar-right">
<!-- start: TO-DO DROPDOWN -->
<li class="dropdown">
  <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" data-close-others="true" href="#">
    <i class="clip-list-5"></i>
    <span class="badge"> 12</span>
  </a>
  <ul class="dropdown-menu todo">
    <li>
      <span class="dropdown-menu-title"> You have 12 pending tasks</span>
    </li>
    <li>
      <div class="drop-down-wrapper">
        <ul>
          <li>
            <a class="todo-actions" href="javascript:void(0)">
              <i class="fa fa-square-o"></i>
              <span class="desc" style="opacity: 1; text-decoration: none;">Staff Meeting</span>
              <span class="label label-danger" style="opacity: 1;"> today</span>
            </a>
          </li>
          <li>
            <a class="todo-actions" href="javascript:void(0)">
              <i class="fa fa-square-o"></i>
              <span class="desc" style="opacity: 1; text-decoration: none;"> New frontend layout</span>
              <span class="label label-danger" style="opacity: 1;"> today</span>
            </a>
          </li>
          <li>
            <a class="todo-actions" href="javascript:void(0)">
              <i class="fa fa-square-o"></i>
              <span class="desc"> Hire developers</span>
              <span class="label label-warning"> tommorow</span>
            </a>
          </li>
          <li>
            <a class="todo-actions" href="javascript:void(0)">
              <i class="fa fa-square-o"></i>
              <span class="desc">Staff Meeting</span>
              <span class="label label-warning"> tommorow</span>
            </a>
          </li>
          <li>
            <a class="todo-actions" href="javascript:void(0)">
              <i class="fa fa-square-o"></i>
              <span class="desc"> New frontend layout</span>
              <span class="label label-success"> this week</span>
            </a>
          </li>
          <li>
            <a class="todo-actions" href="javascript:void(0)">
              <i class="fa fa-square-o"></i>
              <span class="desc"> Hire developers</span>
              <span class="label label-success"> this week</span>
            </a>
          </li>
          <li>
            <a class="todo-actions" href="javascript:void(0)">
              <i class="fa fa-square-o"></i>
              <span class="desc"> New frontend layout</span>
              <span class="label label-info"> this month</span>
            </a>
          </li>
          <li>
            <a class="todo-actions" href="javascript:void(0)">
              <i class="fa fa-square-o"></i>
              <span class="desc"> Hire developers</span>
              <span class="label label-info"> this month</span>
            </a>
          </li>
          <li>
            <a class="todo-actions" href="javascript:void(0)">
              <i class="fa fa-square-o"></i>
              <span class="desc" style="opacity: 1; text-decoration: none;">Staff Meeting</span>
              <span class="label label-danger" style="opacity: 1;"> today</span>
            </a>
          </li>
          <li>
            <a class="todo-actions" href="javascript:void(0)">
              <i class="fa fa-square-o"></i>
              <span class="desc" style="opacity: 1; text-decoration: none;"> New frontend layout</span>
              <span class="label label-danger" style="opacity: 1;"> today</span>
            </a>
          </li>
          <li>
            <a class="todo-actions" href="javascript:void(0)">
              <i class="fa fa-square-o"></i>
              <span class="desc"> Hire developers</span>
              <span class="label label-warning"> tommorow</span>
            </a>
          </li>
        </ul>
      </div>
    </li>
    <li class="view-all">
      <a href="javascript:void(0)">
        See all tasks <i class="fa fa-arrow-circle-o-right"></i>
      </a>
    </li>
  </ul>
</li>
<!-- end: TO-DO DROPDOWN-->
<!-- start: NOTIFICATION DROPDOWN -->
<li class="dropdown">
  <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" data-close-others="true" href="#">
    <i class="clip-notification-2"></i>
    <span class="badge"> 11</span>
  </a>
  <ul class="dropdown-menu notifications">
    <li>
      <span class="dropdown-menu-title"> You have <%= @new_notifications_array.length %> new notifications</span>
    </li>
    <li>
      <div class="drop-down-wrapper">
        <ul>
        <%  for i in 0...@notifications_array.length %>
          <% # new_notif = @notifications %>
            <li>
              <a href="javascript:void(0)">
                <span class="label label-primary"><i class="fa fa-user"></i></span>
                <span class="message"> <%= @notifications_descriptions_array[i].length > 26 ? 
                "#{@notifications_descriptions_array[i][0...20]}..." : @notifications_descriptions_array[i] %></span>
                <span class="time"> <%= ((Time.now-@notifications_array[i].created_at)/(60)).round > 59 ? 
                 ((Time.now-@notifications_array[i].created_at)/(60*60)).round > 24 ? "More than a day ago" : "#{((Time.now-@notifications_array[i].created_at)/(60*60)).round} hr ago"  :  "#{((Time.now-@notifications_array[i].created_at)/(60)).round} min ago"   %> </span>
              </a>
            </li>
        <% end %>
        </ul>
      </div>
    </li>
    <li class="view-all">
      <a href="javascript:void(0)">
        See all notifications <i class="fa fa-arrow-circle-o-right"></i>
      </a>
    </li>
  </ul>
</li>
<!-- end: NOTIFICATION DROPDOWN -->
<!-- start: MESSAGE DROPDOWN -->
<li class="dropdown">
  <a class="dropdown-toggle" data-close-others="true" data-hover="dropdown" data-toggle="dropdown" href="#">
    <i class="clip-bubble-3"></i>
    <span class="badge"> 9</span>
  </a>
  <ul class="dropdown-menu posts">
    <li>
      <span class="dropdown-menu-title"> You have 9 messages</span>
    </li>
    <li>
      <div class="drop-down-wrapper">
        <ul>
          <li>
            <a href="javascript:;">
              <div class="clearfix">
                <div class="thread-image">
                  <img alt="" src="./assets/images/avatar-2.jpg">
                </div>
                <div class="thread-content">
                  <span class="author">Nicole Bell</span>
                  <span class="preview">Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</span>
                  <span class="time"> Just Now</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:;">
              <div class="clearfix">
                <div class="thread-image">
                  <img alt="" src="./assets/images/avatar-1.jpg">
                </div>
                <div class="thread-content">
                  <span class="author"><%= @username %></span>
                  <span class="preview">Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</span>
                  <span class="time">2 mins</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:;">
              <div class="clearfix">
                <div class="thread-image">
                  <img alt="" src="./assets/images/avatar-3.jpg">
                </div>
                <div class="thread-content">
                  <span class="author">Steven Thompson</span>
                  <span class="preview">Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</span>
                  <span class="time">8 hrs</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:;">
              <div class="clearfix">
                <div class="thread-image">
                  <img alt="" src="./assets/images/avatar-1.jpg">
                </div>
                <div class="thread-content">
                  <span class="author">Peter Clark</span>
                  <span class="preview">Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</span>
                  <span class="time">9 hrs</span>
                </div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:;">
              <div class="clearfix">
                <div class="thread-image">
                  <img alt="" src="./assets/images/avatar-5.jpg">
                </div>
                <div class="thread-content">
                  <span class="author">Kenneth Ross</span>
                  <span class="preview">Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</span>
                  <span class="time">14 hrs</span>
                </div>
              </div>
            </a>
          </li>
        </ul>
      </div>
    </li>
    <li class="view-all">
      <a href="pages_messages.html">
        See all messages <i class="fa fa-arrow-circle-o-right"></i>
      </a>
    </li>
  </ul>
</li>
<!-- end: MESSAGE DROPDOWN -->
<!-- start: USER DROPDOWN -->
<li class="dropdown current-user">
  <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" data-close-others="true" href="#">
    <img src="assets/images/avatar-1-small.jpg" class="circle-img" alt="">
    <span class="username"><%= @username %></span>
    <i class="clip-chevron-down"></i>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to " My Profile", edit_user_info_path, class: "clip-user-2" %>
    </li>
    <li class="divider"></li>
    <li>
      <a href="utility_lock_screen.html"><i class="clip-locked"></i>
        &nbsp;Lock Screen </a>
    </li>
    <li>
    <%= link_to " Log Out", destroy_user_session_path, method: :delete, class:  "clip-exit" %>
    </li>
  </ul>
</li>
<!-- end: USER DROPDOWN -->
</ul>
<!-- end: TOP NAVIGATION MENU -->
</div>
</div>
<!-- end: TOP NAVIGATION CONTAINER -->
</div>
<!-- end: HEADER -->

app/views/layouts/_navbar.html.erb
      <div class="navbar-content">
        <!-- start: SIDEBAR -->
        <div class="main-navigation navbar-collapse collapse">
          <!-- start: MAIN MENU TOGGLER BUTTON -->
          <div class="navigation-toggler">
            <i class="clip-chevron-left"></i>
            <i class="clip-chevron-right"></i>
          </div>
          <!-- end: MAIN MENU TOGGLER BUTTON -->
          <!-- start: MAIN NAVIGATION MENU -->
          <ul class="main-navigation-menu">
            <li class="<%= controller.controller_name == "main" ? "active open" : "" %>">                              
                <%= link_to '<i class="clip-home-3"></i> Dashboard'.html_safe, main_path, :class => (controller.controller_name == "main" ? "selected" : "") %>                 
            </li>



            <li class="<%= controller.controller_name == "devices" ? "active open" : "" %>" >
            
              <a href="javascript:void(0)"><i class="clip-screen"></i>
                <span class="title"> Devices </span><i class="icon-arrow"></i>
                <span class="selected"></span>                
              </a>
              <ul class="sub-menu">
                <li class="<%= (controller.controller_name == "devices" && controller.action_name == "index") ? "active open" : "" %>">                  
                  <a href= '<%= devices_path %>'><i class="clip-list"></i>
                    <span class="title"> Devices List </span>
                  </a>              
                </li>

    <!-- Hide create devices link for normal user -->
                <% if current_user.is_admin == 1 %>
                <li>
                  <a href="<%= new_device_path %>"><i class="clip-spinner-2"></i>
                    <span class="title"> Create Devices </span>
                  </a>
                </li>     
                <% end %>

              </ul>
            </li>

            <% if current_user.is_admin == 1 %>
            <li class="<%= controller.controller_name == "requests" ? "active open" : "" %>" >
            
              <a href="javascript:void(0)"><i class="clip-screen"></i>
                <span class="title"> Requests </span><i class="icon-arrow"></i>
                <span class="selected"></span>                
              </a>
              <ul class="sub-menu">
                <li class="<%= (controller.controller_name == "requests" && controller.action_name == "inqueue") ? "active open" : "" %>">                  
                  <a href= '<%= inqueue_requests_path %>'><i class="clip-list"></i>
                    <span class="title"> In Queue </span>
                  </a>              
                </li>

    <!-- Hide create devices link for normal user -->
                <li class="<%= (controller.controller_name == "requests" && controller.action_name == "completed") ? "active open" : "" %>">
                  <a href="<%= completed_requests_path %>"><i class="clip-spinner-2"></i>
                    <span class="title"> Completed Requests </span>
                  </a>
                </li>     

              </ul>
            </li>
            <% end %>


          </ul>
          <!-- end: MAIN NAVIGATION MENU -->
        </div>
        </div>

        <!-- end: SIDEBAR -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

<%= yield %>

  <%= render 'layouts/footer' %>


</body>
</html>

app/views/layouts/controller_layouts.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    (controller.controller_name + 'Controller'), media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag (controller.controller_name + 'Controller'), 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/head' %>
</head>
<body>

  <%= render 'layouts/header' %>

<!-- start: MAIN CONTAINER -->
<div class="main-container">
	<%= render 'layouts/navbar' %>
	<%= yield %>
</div>
		<!-- end: MAIN CONTAINER -->


  <%= render 'layouts/footer' %>


</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>News</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head' %>
  <%= stylesheet_link_tag 'mainController' , media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'mainController', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <%= render 'layouts/navbar' %>
<%= yield %>
  <%= render 'layouts/footer' %>


</body>
</html>